### ISSUE TITLE
fizz3.py errors on run

### ISSUE THREAD

**Issue by aadibajpai** [noops-challenge/fizzbot#10]
Output on running the program:
```
----------------------------------------------------------------------
*** GET /fizzbot
Traceback (most recent call last):
  File "C:\Users\aadibajpai\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Users\aadibajpai\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\aadibajpai\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\aadibajpai\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\aadibajpai\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1016, in _send_output
    self.send(msg)
  File "C:\Users\aadibajpai\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 956, in send
    self.connect()
  File "C:\Users\aadibajpai\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Users\aadibajpai\AppData\Local\Programs\Python\Python37\lib\socket.py", line 727, in create_connection
    raise err
  File "C:\Users\aadibajpai\AppData\Local\Programs\Python\Python37\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\aadibajpai\Desktop\fizz.py", line 76, in <module>
    if __name__ == '__main__': main()
  File "C:\Users\aadibajpai\Desktop\fizz.py", line 74, in main
    question_url = do_question(domain, question_url)
  File "C:\Users\aadibajpai\Desktop\fizz.py", line 60, in do_question
    request = urllib.request.urlopen( ('%s%s' % (domain, question_url)) )
  File "C:\Users\aadibajpai\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\aadibajpai\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Users\aadibajpai\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "C:\Users\aadibajpai\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\aadibajpai\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 1345, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Users\aadibajpai\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>
```
Not sure how to fix.

**Comment by quentinms** [comment]
@aadibajpai It's because it uses a localhost domain instead of the real one, see #11 for a fix.

**Comment by aadibajpai** [comment]
Ahh, I thought the localhost domain was to run an interactive local app or something. I need some sleep 🤦🏻‍♂️
